import type { Candidate, MicroTask, TimelineStep } from "./types";

export const sampleCandidates: Candidate[] = [
  {
    id: "cand-a104",
    codeName: "Analyst #A104",
    initials: "RS",
    college: "IIT Kharagpur",
    year: "3rd year",
    skills: ["SQL", "Python", "Power BI"],
    vettingScore: 94,
    sprintsCompleted: 3,
    status: "vetted",
    topPercentile: 5,
  },
  {
    id: "cand-a087",
    codeName: "Analyst #A087",
    initials: "PN",
    college: "NMIMS Mumbai",
    year: "2nd year",
    skills: ["Excel", "Power BI", "SQL"],
    vettingScore: 88,
    sprintsCompleted: 1,
    status: "in_sprint",
  },
  {
    id: "cand-a112",
    codeName: "Analyst #A112",
    initials: "KM",
    college: "KCC Institute of Technology",
    year: "Final year",
    skills: ["Python", "ETL", "SQL"],
    vettingScore: 91,
    sprintsCompleted: 5,
    status: "completed",
    topPercentile: 10,
  },
  {
    id: "cand-a129",
    codeName: "Analyst #A129",
    initials: "SV",
    college: "Christ University",
    year: "3rd year",
    skills: ["Tableau", "SQL", "Excel"],
    vettingScore: 90,
    sprintsCompleted: 2,
    status: "vetted",
    topPercentile: 8,
  },
];

export const sampleTasks: MicroTask[] = [
  {
    id: "task-1",
    title: "Clean and de-duplicate a 40k-row customer export",
    companyStage: "Seed-stage D2C brand",
    skills: ["Excel", "SQL"],
    durationDays: 6,
    budgetMin: 2500,
    budgetMax: 4000,
    vettedInterested: 14,
    status: "open",
  },
  {
    id: "task-2",
    title: "Build a churn cohort dashboard from raw event logs",
    companyStage: "Series A fintech",
    skills: ["Python", "Power BI"],
    durationDays: 10,
    budgetMin: 3500,
    budgetMax: 5000,
    vettedInterested: 21,
    status: "filling",
  },
  {
    id: "task-3",
    title: "Automate a weekly supplier pricing scraper",
    companyStage: "Bootstrapped B2B marketplace",
    skills: ["Python", "ETL"],
    durationDays: 8,
    budgetMin: 3000,
    budgetMax: 4500,
    vettedInterested: 9,
    status: "open",
  },
  {
    id: "task-4",
    title: "Reconcile Q2 ad spend across three platforms",
    companyStage: "Pre-seed D2C brand",
    skills: ["Excel", "SQL"],
    durationDays: 5,
    budgetMin: 1500,
    budgetMax: 2500,
    vettedInterested: 17,
    status: "open",
  },
];

export const timelineSteps: TimelineStep[] = [
  {
    id: "step-1",
    number: "01",
    title: "A 30-minute practical task",
    body: "No resumes, no pedigree filters. Candidates prove competency on hands-on SQL, Python, and data-cleaning tasks — scored objectively.",
  },
  {
    id: "step-2",
    number: "02",
    title: "A paid micro-internship",
    body: "Selected analysts execute a scoped 5–15 day backlog task for a live startup, with the budget held in escrow from day one.",
  },
  {
    id: "step-3",
    number: "03",
    title: "Long-term hire or PPO",
    body: "Founders evaluate real, delivered work — not an interview performance. High performers convert directly into a role.",
  },
];
